# Generated by Django 6.0.1 on 2026-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_city_city_name_en_city_city_name_ru_city_region_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_registered',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
