# Generated by Django 6.0.1 on 2026-01-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_userprofile_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_registered',
            field=models.DateField(null=True),
        ),
    ]
