# Generated by Django 6.0.1 on 2026-01-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0005_alter_userprofile_date_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_registered',
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
    ]
