# Generated by Django 6.0.1 on 2026-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0006_remove_userprofile_date_registered_review_comment_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
