# Generated by Django 6.0.1 on 2026-01-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0007_userprofile_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_ru',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_date',
        ),
    ]
